version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  scraper:
    build: .
    depends_on:
      - db
    volumes:
      - ./dumps:/app/dumps
    command: python scraper.py